
# curl -X POST -H "Content-Type: application/json" -d '{"order": "example"}' http://localhost:3001/create-order

###
POST http://127.0.0.1:3001/create-order HTTP/1.1
content-type: application/json

{
    "order": "test"
}


###
GET http://127.0.0.1:3001/test HTTP/1.1

